# Time limit for the game to end, in seconds
gameTime: 300

# Frag limit for the game to end
maxFrags: 20

# Time for the game to start after having the minimum amount of players
timeToStart: 20

# Respawn time after getting fragged
respawnTime: 3

# The maximum number of players for an arena
maxPlayers: 4

# Messages that show when a player is fragged. The message selected is random and can be from either the first list only, or both.
# Make sure to add a space at the end of the first message.
# Feel free to use colours with &<colour id>.
# The first %s represents the player that killed. The second %s represents the player that was killed.
deathMessages1:
   - "&f%s died to %s."
   - "&f%s was destroyed by %s!"
   - "&f%s was killed by %s!"
   - "&f%s was obliterated by %s!"
   - "&f%s has fallen to %s."
   - "&f%s was gibbed by %s."
deathMessages2:
   - "Perhaps they should stick to building."
   - "Aim diff."
   - "Sit."
   - "Clearly they struggle with clicking."
   - "Someone tell them to turn on their monitor."
   - "Are they even trying?"
   - "Yikes."
   - "I think they might need glasses."
   - "Lmao."
   - "Hold that L."
   
fell_off_message: "&f%s fell off. Literally."
knocked_off_message: "&f%s knocked %s off the arena!"

### SQL Connection ### Ignore if you do NOT have an SQL Server. ###   
host: "localhost" # SQL Host IP
port: "3306" # SQL Port
database: "gibcraft" # Database where player stats will be stored. It is recommended that you create a new database for each plugin that uses SQL.
username: "" # SQL Username
password: "" # SQL Password
useSSL: false 
# Plugin will ALWAYS save to the database IF it is connected. But will only save to local files IF you want it to OR SQL is NOT connected.
localSave: true # If set to true, player stats will be saved locally AND in the SQL database, IF SQL is connected.
loadFromSQL: false # If set to true, player stats will ONLY load from the SQL database, even though they may or may not be saved on the database and locally.
# Warning: Turning both of the previous options to FALSE will save the player stats to the database but ONLY load locally, which will result in a stat reset every time.
###################################################################