main: me.guitarxpress.gibcraft.GibCraft
name: GibCraft
version: 1.1.1
authors: [GuitarXpress, haloman30]
api-version: 1.20
description: A minigame based on Ratz InstaGib and Quake. 
depend: [ProtocolLib]

commands:
   gibcraft:
      aliases: gib
      usage: /<command>